C4Context
    accTitle: Shop System
    accDescr: Containers

    Person(person, "Customer", "Customer who is buying a product online")

    System_Boundary(webApp, "Shop", "Allows customers to search, view and purchase products") {
        Container(webApp, "Web Application", "HTML", "Web frontend for buying a product")
        Container(api, "API Application", "API Gateway", "API that manages product details")
        ContainerDb(db, "Database", "DynamoDB", "Tables to store product and customer data")

        Rel(webApp, api, "Makes calls to", "JSON-RPC")
        Rel(api, db, "Reads and writes to", "JSON-RPC")
    }

    Rel(person, webApp, "Visits", "JSON-RPC")
